version: '2'
services:
  client-summary-cwa:
    image: combined-registry.sbx.zone/client-summary-cwa:0.1.0-12
    expose:
      - "3000"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
